# server
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      
# view resolver
spring:
  mvc:
    view:
      prefix: /WEB-INF/webtest
      suffix: .jsp
      
# DataBase
  datasource:
    url: jdbc:mysql://localhost:3306/market?severTimezone=UTC"
    username: root
    password: 1111
  jpa:
    show-sql: true
    
